include("../jacobi_method/jacobiMethod.jl")
include("../power_method/powerMethod.jl")
include("../qr_method/qrMethod.jl")

using Pkg
Pkg.add("BenchmarkTools")
using BenchmarkTools

matrix1 = Array(Symmetric(rand(5, 5) * 100))
matrix2 = Array(Symmetric(rand(25, 25) * 100))
matrix3 = Array(Symmetric(rand(75, 75) * 100))
matrix4 = Array(Symmetric(rand(150, 150) * 100))

printstyled("JACOBI METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark jacobiMethod(matrix1))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark jacobiMethod(matrix2))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark jacobiMethod(matrix3))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark jacobiMethod(matrix4))
println()
println()

printstyled("POWER METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark powerMethod(matrix1))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark powerMethod(matrix2))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark powerMethod(matrix3))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark powerMethod(matrix4))
println()
println()

printstyled("POWER METHOD WITH DEFLATION:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(matrix1))
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(matrix2))
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(matrix3))
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(matrix4))
println()
println()

printstyled("QR METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark qrMethod(matrix1))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark qrMethod(matrix2))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark qrMethod(matrix3))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark qrMethod(matrix4))
println()
