include("../jacobi_method/jacobiMethod.jl")
include("../power_method/powerMethod.jl")
include("../qr_method/qrMethod.jl")

using Pkg
Pkg.add("BenchmarkTools")
using BenchmarkTools

get_matrix5x5() = Array(Symmetric(rand(5, 5) * 100))
get_matrix25x25() = Array(Symmetric(rand(25, 25) * 100))
get_matrix75x75() = Array(Symmetric(rand(75, 75) * 100))
get_matrix150x150() = Array(Symmetric(rand(150, 150) * 100))

printstyled("JACOBI METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark jacobiMethod(entryMatrix) setup=(entryMatrix=get_matrix5x5()))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark jacobiMethod(entryMatrix) setup=(entryMatrix=get_matrix25x25()))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark jacobiMethod(entryMatrix) setup=(entryMatrix=get_matrix75x75()))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark jacobiMethod(entryMatrix) setup=(entryMatrix=get_matrix150x150()))

println()

printstyled("POWER METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark powerMethod(entryMatrix) setup=(entryMatrix=get_matrix5x5()))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark powerMethod(entryMatrix) setup=(entryMatrix=get_matrix25x25()))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark powerMethod(entryMatrix) setup=(entryMatrix=get_matrix75x75()))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark powerMethod(entryMatrix) setup=(entryMatrix=get_matrix150x150()))

println()

printstyled("POWER METHOD WITH DEFLATION:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(entryMatrix) setup=(entryMatrix=get_matrix5x5()))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(entryMatrix) setup=(entryMatrix=get_matrix25x25()))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(entryMatrix) setup=(entryMatrix=get_matrix75x75()))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark powerMethodWithDeflation(entryMatrix) setup=(entryMatrix=get_matrix150x150()))

println()

printstyled("QR METHOD:\n", color = :(green))
printstyled("Matrix 5x5:\n", color = :(blue))
display(@benchmark qrMethod(entryMatrix) setup=(entryMatrix=get_matrix5x5()))
println()
printstyled("Matrix 25x25:\n", color = :(blue))
display(@benchmark qrMethod(entryMatrix) setup=(entryMatrix=get_matrix25x25()))
println()
printstyled("Matrix 75x75:\n", color = :(blue))
display(@benchmark qrMethod(entryMatrix) setup=(entryMatrix=get_matrix75x75()))
println()
printstyled("Matrix 150x150:\n", color = :(blue))
display(@benchmark qrMethod(entryMatrix) setup=(entryMatrix=get_matrix150x150()))
